# .github/workflows/delete-runs.yml
name: Delete old workflow runs

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天午夜执行一次

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: actions/delete-workflow-runs@v4
        with:
          # 用于认证的 GitHub Token
          token: ${{ secrets.GITHUB_TOKEN }}
          # 要删除运行记录的仓库，默认为当前仓库
          repository: ${{ github.repository }}
          # 保留最近 90 天的运行记录
          retain_days: 10
          # 至少保留 5 次运行记录，即使它们超过了 retain_days
          keep_minimum_runs: 3
          # 是否删除与工作流运行相关的日志文件
          delete_run_artifacts: false
