name: Cleanup Old Workflow Runs

on:
  # 每天凌晨执行一次，或者根据你的需要调整
  schedule:
    - cron: '0 0 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  delete-old-runs:
    runs-on: ubuntu-latest
    # **重要**：必须添加这个权限，否则 Action 无权删除记录
    permissions:
      actions: write
      
    steps:
      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@v1.2.0 # 使用一个稳定且有效的 Action
        with:
          # GitHub Token 是必需的，用于授权
          retoken: ${{ secrets.GITHUB_TOKEN }}
          # 保留最近 7 天的记录
          retain_days: 2
          # 但无论天数如何，始终保留最近的 3 次运行记录
          keep_minimum_runs: 3
